### ISSUE TITLE
Getting possible mock file paths can result in a collision

### ISSUE THREAD

**Issue by marijnz0r** [swisnl/php-http-fixture-client#1]
Endpoint 1: 
api/endpoint?foo_bar_fizz=buzz

Endpoint 2:
api/endpoint?foo=bar&fizz=buzz

Getting possible mock file paths for both the endpoints will result in the same mock file:
api/endpoint.foo-bar-fizz-buzz.mock

I think changes need to be made in the getQueryFromRequst method in the ResponseBuilder.

**Comment by bbrala** [comment]
Do you have an proposal on how we should build the paths so we can fix these collisions?

**Comment by JaZo** [comment]
The problem is that an URI is allowed to contain more characters (see http://tools.ietf.org/html/rfc3986#section-2) than a (cross platform) filename. This makes collisions inevitable. However, we can make the collisions less frequent by separating the GET-params using a different character and by separating the key and value using an obscure character that isn't widely used in URIs.

@marijnz0r, @bbrala, do you think something like this would help?

Endpoint 1:
`api/endpoint.foo_bar_fizz~buzz.mock`

Endpoint 2:
`api/endpoint.foo~bar.fizz~buzz.mock`

**Comment by bbrala** [comment]
I think that should work, though perhaps making the endpoint a directory for parameters would make things even better.

`api/endpoint/foo_bar_fizz~buzz.mock`

`api/endpoint/foo~bar.fizz~buzz.mock`

Without parameters

`api/endpoint.mock`

This way parameters and endpoints will not interfere with eachother.

**Comment by marijnz0r** [comment]
That's a nice solution! I think it's important to explain it in the readme thoroughly, because it will be more difficult for users to create the correct mock files this way.

**Comment by JaZo** [comment]
@bbrala using a directory for URIs with GET-params might help, but can also introduce more collisions.

api/endpoint?foo
`api/endpoint/foo.mock`

api/endpoint/foo
`api/endpoint/foo.mock`

@marijnz0r I'm thinking of creating a small JS-helper which converts a given URI to a filepath using the same rules as this client.

**Comment by bbrala** [comment]
Hmm good point...

Technically `&` is allowed in the filename, perhaps we are overcomplicating it by tring to replace the seperator for the query parameters.

**Comment by JaZo** [comment]
`=` is also allowed, so it's best if we just leave it at `=` and `&` and only replace characters in the key/value! 😄 

api/endpoint?foo=bar&fizz=buzz
`api/endpoint.foo=bar&fizz=buzz.mock`

I'll create a PR for this!
