### ISSUE TITLE
possibility to have different fixtures for same endpoint

### ISSUE THREAD

**Issue by Fivell** [swisnl/php-http-fixture-client#5]
## Detailed description

I have path api-example.com/orders.json
I need 2 tests for 2 cases
1)  successful order creation 
2) order was not created for some reason (response contains reason)

while reading docs I didn't find any example how to achieve it
## Context

Same http endpoint can respond with big variety of responses that means different logic for client

**Comment by bbrala** [comment]
This is a valid point, we'll look into possible solutions. For now you could the fixtures by success/fail and load a different fixtures path until we have a working solution.

**Comment by JaZo** [comment]
@Fivell, I think it is hard to determine which response should be returned at which time if the uri is the same. Do you have an idea for a possible implementation?

You can use different fixture paths as suggested by @bbrala. Besides, this client extends [php-http/mock-client](https://github.com/php-http/mock-client). This allows you to add custom responses (or exceptions) that ignore the fixtures.

```php
$client = new \Swis\Http\Fixture\Client(...);
$response = $this->createMock('Psr\Http\Message\ResponseInterface');
$client->addResponse($response);

$client->sendRequest(new Request(...)); // uses above response from queue
$client->sendRequest(new Request(...)); // uses fixture file
```

N.B. You can't use a default response for the mock client because this client uses that to set the response from the fixture.

**Comment by JaZo** [comment]
I have added a note about the underlying mock-client to the readme: https://github.com/swisnl/php-http-fixture-client/blob/master/README.md#mocks-advanced

**Comment by Fivell** [comment]
@JaZo  
>>  I think it is hard to determine which response should be returned at which time if the uri is the same. Do you have an idea for a possible implementation?

I didn't dig into implementation of current library (i even not a php guy for ages) but for sure the only way is to also take request body into a account not only method/path,  also we finally succeed with php-vcr library  (which stores yaml files with both requests and responses in fuxtures) when test our api client.

Feel free to close this issue since you find a way to do it ignoring fixtures and we find more complex library for our needs

**Comment by JaZo** [comment]
I'm closing this issue because alternatives exist and this can't be fixed using the current matching strategy i.e. mapping a request (body) to a static file.
